## Copyright (C) 2026 Mark Robillard Jr (MARKMENTAL)
## SPDX-License-Identifier: GPL-3.0-or-later
# 1. You only need mod_proxy enabled for this
server.modules += ( "mod_proxy" )

# 2. Trap the /proxy/ prefix from the user's HTTP request, map the path, and forward it
# to the proxy passed application server
$HTTP["url"] =~ "^/proxy/" {
    proxy.header = (
        "map-urlpath" => ( "/proxy/" => "/" )
    )
    proxy.server = (
        "" => ( ( "host" => "127.0.0.1", "port" => 1337 ) )
    )
}

